### ISSUE TITLE
if data is not reactive please don't add it to Vue

### ISSUE THREAD

**Issue by juanbrujo** [Zenemig/zenemig#4]
https://github.com/Zenemig/zenemig/blob/master/src/views/Home.vue#L24

Vue is gooooood with data-binding. If it will not mutate, use it directly in `<template></template>`

**Comment by juanbrujo** [comment]
ok for that reason. you can always import an .json with the data and iterate over it

**Comment by Zenemig** [comment]
My plan is to create a CMS behind a login for managing projects and a few other contents and then I'll be moving it away from the data object.
